CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  img_size: [3, 256, 256]
DATA:
  root: "../data"
  batch_size: 1
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.00005
  weight_decay_step: 100
  num_epochs: 100