CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  embed_size: 256
  num_output_tokens: 1
  num_decoder_layers: 1
  num_frequencies: 1
  dropout: 0.1
  img_size: [3, 224, 224]
  loss_weights:
    mask_pred_loss_weight: 1
    iou_loss_weight: 0
DATA:
  root: "../data"
  batch_size: 128
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.00005
  weight_decay_step: 100
  num_epochs: 100